%The sequence of triangle numbers is generated by adding the natural numbers.
%So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
%The first ten terms would be:1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

%Let us list the factors of the first seven triangle numbers:
% 1: 1
% 3: 1,3
% 6: 1,2,3,6
% 10: 1,2,5,10
% 15: 1,3,5,15
% 21: 1,3,7,21
% 28: 1,2,4,7,14,28
% We can see that 28 is the first triangle number to have over five divisors.
% 
% What is the value of the first triangle number to have over five hundred divisors?
% use n=1e4, in cow32 i is from 1 to 1e4 by about 5600 seconds,
% loading in tens.mat
clear,clc;
tic
n=2e4;
trinumbox=zeros(n,1);
for i=1:n
    trinumbox(i)=i;
end
temp=trinumbox;
for i= 2:n
    for j=1:i-1
        trinumbox(i)=trinumbox(i)+temp(j);
    end
end
maxflag=480;maxi=5984;
for i=11624:n
    i
    flag=0;
    for j=1:trinumbox(i)
        if mod(trinumbox(i),j)==0
            flag=flag+1;
        end
    end
    if flag>maxflag
        maxflag=flag;
        maxi=i;
    end
    if flag>500
        break;
    end
end
toc
maxflag
trinumbox(maxi)

