%%
%Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
%By starting with 1 and 2, the first 10 terms will be:
%1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

%%
%By considering the terms in the Fibonacci sequence whose values--
%do not exceed four million, find the sum of the even-valued terms.

clc;clear;
k0=1;k1=1;sum=0;
while k1<=4000000
    k2=k0+k1;
    k0=k1;
    k1=k2;
    if mod(k2,2)==0&&k2<=4000000
       sum=sum+k2;
    end
end
sum